### PR TITLE
Fix leading slash in ZIP archive

### LINKED ISSUE #102: ZipArchiveFileSystem produces files that cannot be unzipped on windows
From https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.ziparchive.createentry?view=net-9.0:

> The entryName string should reflect the relative path of the entry you want to create within the zip archive. There is no restriction on the string you provide. However, if it is not formatted as a relative path, the entry is created, but you may get an exception when you extract the contents of the zip archive.

This line uses the absolute path:

https://github.com/xoofx/zio/blob/c669e680d8abfa734ee3df0c249a13760f4e4bcd/src/Zio/FileSystems/ZipArchiveFileSystem.cs#L911

Code to reproduce:

```cs
using var zipFileSystem = new ZipArchiveFileSystem("testing.zip", compressionLevel: CompressionLevel.Optimal);
var file = new FileEntry(zipFileSystem, UPath.Root / "testing.txt");
file.WriteAllText("abc");
```

Opening the archive in 7zip:

Image

When trying to extract with default windows context menu:

Image

7zip can extract the files, seems like it handles empty directory names okay.

### PR DESCRIPTION
**Pull request by GerardSmit**
Fixes #102

## Backward Compatibility
When you've created a ZIP archive with version <0.21, all entries will start with a `/` in the entry name.

To ensure we don't mismatch new entry names, I've introduced a new property:

```cs
class ZipArchiveFileSystem
{
	/// <summary>
	///    Gets or sets whether entries in the archive should have a leading slash.
	/// </summary>
	/// <exception cref="InvalidOperationException">Cannot change LeadingSlashInArchive when the archive already contains entries</exception>
	public bool LeadingSlashInArchive { get; set; }
}
```

When opening a ZIP archive from version <0.21 (or when there is a leading slash in the ZIP entry name), this property will be set to `true`.
For new ZIP file systems, it will be set to `false`. **⚠️ (This is a breaking change)**

When this property is set to `true`, all new entries will have a leading slash.

I've created two ZIPs (one before the change and one after the change) to validate that both the old and new ZIPs work correctly.

## Recursive Rename/Deletion
While debugging, I found another bug.

When you have a directory name that starts with the same prefix as other directories in the same path, it would:
1. Move the wrong directories.
2. Delete the wrong directories.

For example:
```
dir\
	file.txt

dir-suffix\
	file.txt

unrelated\
	file.txt
```
When you remove `dir\`, it would also remove `dir-suffix\`. This obviously shouldn't happen.

## Other Changes
1. Moved test ZIPs to sub-directories and added a README explaining the content.
2. When moving directories, we don't copy the entry Stream (which is empty; it's a directory..) anymore.
3. Added .NET FX target back in Unit Tests (otherwise, I couldn't validate .NET Standard 2.0 / .NET FX).

**Note:** .NET Standard 2.1 is not being tested. .NET 8.0 and 9.0 have a direct match, and .NET 10.0 uses the .NET 9.0 library version.

### CODE REVIEW

File: src/Zio/FileSystems/ZipArchiveFileSystem.cs [hunk 1]
```diff
@@ -918,6 +957,50 @@ private ZipArchiveEntry CreateEntry(UPath path, bool isDirectory = false)
...
+        }
+#else
+        var length = LeadingSlashInArchive ? path.FullName.Length : path.FullName.Length - 1;
+
+        if (isDirectory)
+        {
+            length += 1; // add trailing slash
+        }
+
+        var archivePath = string.Create(length, (LeadingSlashInArchive, isDirectory, path), static (span, ctx) =>
```
Comment (GerardSmit) [inline src/Zio/FileSystems/ZipArchiveFileSystem.cs:984]: I'm not sure if this is the right way to do in .NET (10).

In .NET 10 we have that the tiered JIT is smart enough to allocate arrays on the stack (when possible), but I'm not sure about strings. Maybe it's better to do this as well for .NET?

```cs
var archivePath = LeadingSlashInArchive ? path.FullName : path.FullName.Substring(1);

if (isDirectory)
{
    archivePath += DirectorySeparator;
}
```

And it's 1. easier to read, 2. less code to maintain 😄

Comment (xoofx) [reply src/Zio/FileSystems/ZipArchiveFileSystem.cs:984]: I think the code is ok. Thanks for trying to use a less allocatey path for .NET
